name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kotlin/Gradle environment
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test --info

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: composeApp/build/test-results/test

  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kotlin/Gradle environment
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run desktop UI tests
        run: ./gradlew desktopTest --info

      - name: Upload UI test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-report
          path: composeApp/build/test-results/desktopTest

  publish-test-report:
    runs-on: ubuntu-latest
    needs: [ unit-tests, ui-tests ]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download unit test report
        uses: actions/download-artifact@v4
        with:
          name: unit-test-report
          path: reports/unit

      - name: Download UI test report
        uses: actions/download-artifact@v4
        with:
          name: ui-test-report
          path: reports/ui

      - name: Upload test reports as Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports

  deploy:
    runs-on: ubuntu-latest
    needs: publish-test-report
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
