name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kotlin/Gradle environment
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kotlin/Gradle environment
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run desktop UI tests
        run: ./gradlew desktopTest
